version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  zosma-sd-worker:
    <<: *base_service
    restart: always
    profiles: ["worker"]
    build: ./services/AUTOMATIC1111
    image: zosma-sd-worker
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  zosma-sd-workershim:
    profiles: ["worker"]
    restart: always
    depends_on:
      - zosma-sd-worker
    image: mcntech/zosma-sd-workershim:v0.02
    env_file:
      - .env

